export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  GITHUB_CALLBACK: '/auth/github/callback',
  CHANGE_PASSWORD: '/change-password',
  SET_PASSWORD: '/set-password',
  WELCOME: '/welcome',
  HOME: '/home',
  MOCK_INTERVIEW: '/mock-interview',
  RESUME_ANALYZER: '/resume-analyzer',
  AI_MENTOR: '/ai-mentor',
  DASHBOARD: '/dashboard',
}